package com.cyberelephant.bank.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFF840076)
val md_theme_dark_onPrimary = Color(0xFFFFACE8)
val md_theme_dark_primaryContainer = Color(0xFFFFACE8)
val md_theme_dark_onPrimaryContainer = Color(0xFF840076)
val md_theme_dark_secondary = Color(0xFF7FD0FF)
val md_theme_dark_onSecondary = Color(0xFF00344A)
val md_theme_dark_secondaryContainer = Color(0xFF004C6A)
val md_theme_dark_onSecondaryContainer = Color(0xFFC5E7FF)
val md_theme_dark_tertiary = Color(0xFFE1B6FF)
val md_theme_dark_onTertiary = Color(0xFF461968)
val md_theme_dark_tertiaryContainer = Color(0xFF5E3280)
val md_theme_dark_onTertiaryContainer = Color(0xFFF2DAFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF2B0052)
val md_theme_dark_onBackground = Color(0xFFEFDBFF)
val md_theme_dark_surface = Color(0xFF2B0052)
val md_theme_dark_onSurface = Color(0xFFEFDBFF)
val md_theme_dark_surfaceVariant = Color(0xFF140224)
val md_theme_dark_onSurfaceVariant = Color(0xFFD2C2CA)
val md_theme_dark_outline = Color(0xFF9B8D94)
val md_theme_dark_inverseOnSurface = Color(0xFF2B0052)
val md_theme_dark_inverseSurface = Color(0xFFEFDBFF)
val md_theme_dark_inversePrimary = Color(0xFFAD009A)
val md_theme_dark_surfaceTint = Color(0xFFFFACE8)
val md_theme_dark_outlineVariant = Color(0xFF4F444A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFC724B1)
